database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/',views.logout,name='logout'),
]

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/book_review_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('libraries/', include('libraries.urls')),
    path('accounts',include('accounts.urls'))
]

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/libraries/urls.py
from django.urls import path
from . import views


app_name = 'libraries'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_pk>/', views.detail, name='detail'),
    path('<int:book_pk>/review_create/', views.review_create, name='review_create'),
    path(
        '<int:book_pk>/review/<int:review_pk>/delete/',
        views.review_delete,
        name='review_delete',
    ),]

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/libraries/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/libraries/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content',)

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
\
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm



# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('libraries:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('libraries:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('libraries:index')

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/libraries/views.py
from django.shortcuts import render,redirect
from .models import Book,Review
from .forms import ReviewForm
# Create your views here.
def index(request):
    books = Book.objects.all()
    context = {
        'books': books
    }
    return render(request, 'libraries/index.html', context)

def detail(request, book_pk):
    book = Book.objects.get(pk=book_pk)
    reviews = book.review_set.all()
    review_form = ReviewForm()
    context = {
        'book': book,
        'reviews':reviews,
        'review_form':review_form,

    }
    return render(request, 'libraries/detail.html', context)

def review_create(request, book_pk):
    book = Book.objects.get(pk=book_pk)
    reviews = book.review_set.all()
    review_form = ReviewForm(request.POST)
    if review_form.is_valid():
        review = review_form.save(commit=False)
        review.book = book
        review.user = request.user
        review.save()
        return redirect('libraries:detail', book.pk)
    context = {
        'review_form': review_form,
        'book': book,
        'reviews': reviews,
    }
    return render(request, 'libraries/detail.html', context)


def review_delete(request, book_pk, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        review.delete()
    return redirect('libraries:detail', book_pk)

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/libraries/templates/libraries/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>책 상세 정보</h1>
  <p>등록 번호 : {{ book.pk }}</p>
  <p>제목 : {{ book.title }}</p>
  <p>설명 : {{ book.description }}</p>
  <hr>
  <h3>리뷰 등록</h3>
  <form action="{% url "libraries:review_create" book.pk %}" method="POST">
    {% csrf_token %}
    {{ review_form }}
    <input type="submit" value="리뷰 작성">
  </form>
  <hr>
  <h3>리뷰 전체 목록 </h3>
  <ul>
    {% for review in reviews %}
      <li>
        {{review.user}} - {{ review.content }}
        {% if request.user == review.user %}
        <form action="{% url "libraries:review_delete" book.pk review.pk %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <input type="submit" value="리뷰 삭제">
        </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  <hr>
  <a href="{% url "libraries:index" %}">[back]</a>
{% endblock content %}

database/02-02-many-to-one-relationship/assignment/DB_hw_4_4/libraries/templates/libraries/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>책 전체 목록</h1>
  <ul>
    {% for book in books %}
      <a href="{% url 'libraries:detail' book.pk %}">
        <li>제목 : {{ book.title }}</li>
      </a>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}